# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto3.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto3.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cproto3.proto*J\n\x11\x45xampleProto3Enum\x12\x10\n\x0c\x46IRST_CHOICE\x10\x00\x12\x11\n\rSECOND_CHOICE\x10\x01\x12\x10\n\x0cTHIRD_CHOICE\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_EXAMPLEPROTO3ENUM = _descriptor.EnumDescriptor(
  name='ExampleProto3Enum',
  full_name='ExampleProto3Enum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIRST_CHOICE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECOND_CHOICE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THIRD_CHOICE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=16,
  serialized_end=90,
)
_sym_db.RegisterEnumDescriptor(_EXAMPLEPROTO3ENUM)

ExampleProto3Enum = enum_type_wrapper.EnumTypeWrapper(_EXAMPLEPROTO3ENUM)
FIRST_CHOICE = 0
SECOND_CHOICE = 1
THIRD_CHOICE = 2


DESCRIPTOR.enum_types_by_name['ExampleProto3Enum'] = _EXAMPLEPROTO3ENUM


# @@protoc_insertion_point(module_scope)
